### ISSUE TITLE
Bookmarklet does not work on ChromiumEdge

### ISSUE THREAD

**Issue by ktaaaki** [ktaaaki/paper2html#14]

**Comment by eitsupi** [comment]
It works from favorites bar, but not from favorites button.

**Comment by ktaaaki** [comment]
Yes, the bookmarklet is activated when you press a favorite item in the bar.
It does not work when you add a page to favorites.

This issue was our mistake.

**Comment by ktaaaki** [comment]
The "Favorites button" is the button next to the "Add to Favorites" star icon. (my mistake)
The issue still remains.
